# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cpuaffinity.ui'
#
# Created: Sat Nov 24 20:29:38 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_affinityDialog(object):
    def setupUi(self, affinityDialog):
        affinityDialog.setObjectName(_fromUtf8("affinityDialog"))
        affinityDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        affinityDialog.resize(358, 320)
        affinityDialog.setWindowTitle(QtGui.QApplication.translate("affinityDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(affinityDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(affinityDialog)
        self.groupBox.setTitle(QtGui.QApplication.translate("affinityDialog", "Current CPU affinity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBox_0 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_0.setText(QtGui.QApplication.translate("affinityDialog", "CPU0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_0.setObjectName(_fromUtf8("checkBox_0"))
        self.gridLayout.addWidget(self.checkBox_0, 0, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_8.setText(QtGui.QApplication.translate("affinityDialog", "CPU8", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 0, 1, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_16.setText(QtGui.QApplication.translate("affinityDialog", "CPU16", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout.addWidget(self.checkBox_16, 0, 2, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_24.setText(QtGui.QApplication.translate("affinityDialog", "CPU24", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridLayout.addWidget(self.checkBox_24, 0, 3, 1, 1)
        self.checkBox_1 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_1.setText(QtGui.QApplication.translate("affinityDialog", "CPU1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridLayout.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_9.setText(QtGui.QApplication.translate("affinityDialog", "CPU9", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 1, 1, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_17.setText(QtGui.QApplication.translate("affinityDialog", "CPU17", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout.addWidget(self.checkBox_17, 1, 2, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_25.setText(QtGui.QApplication.translate("affinityDialog", "CPU25", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout.addWidget(self.checkBox_25, 1, 3, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_2.setText(QtGui.QApplication.translate("affinityDialog", "CPU2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_10.setText(QtGui.QApplication.translate("affinityDialog", "CPU10", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 2, 1, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_18.setText(QtGui.QApplication.translate("affinityDialog", "CPU18", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridLayout.addWidget(self.checkBox_18, 2, 2, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_26.setText(QtGui.QApplication.translate("affinityDialog", "CPU26", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridLayout.addWidget(self.checkBox_26, 2, 3, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_3.setText(QtGui.QApplication.translate("affinityDialog", "CPU3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_11.setText(QtGui.QApplication.translate("affinityDialog", "CPU11", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 3, 1, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_19.setText(QtGui.QApplication.translate("affinityDialog", "CPU19", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridLayout.addWidget(self.checkBox_19, 3, 2, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_27.setText(QtGui.QApplication.translate("affinityDialog", "CPU27", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridLayout.addWidget(self.checkBox_27, 3, 3, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_4.setText(QtGui.QApplication.translate("affinityDialog", "CPU4", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_12.setText(QtGui.QApplication.translate("affinityDialog", "CPU12", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 4, 1, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_20.setText(QtGui.QApplication.translate("affinityDialog", "CPU20", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout.addWidget(self.checkBox_20, 4, 2, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_28.setText(QtGui.QApplication.translate("affinityDialog", "CPU28", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.gridLayout.addWidget(self.checkBox_28, 4, 3, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_5.setText(QtGui.QApplication.translate("affinityDialog", "CPU5", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_13.setText(QtGui.QApplication.translate("affinityDialog", "CPU13", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 5, 1, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_21.setText(QtGui.QApplication.translate("affinityDialog", "CPU21", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridLayout.addWidget(self.checkBox_21, 5, 2, 1, 1)
        self.checkBox_29 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_29.setText(QtGui.QApplication.translate("affinityDialog", "CPU29", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.gridLayout.addWidget(self.checkBox_29, 5, 3, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_6.setText(QtGui.QApplication.translate("affinityDialog", "CPU6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 6, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_14.setText(QtGui.QApplication.translate("affinityDialog", "CPU14", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout.addWidget(self.checkBox_14, 6, 1, 1, 1)
        self.checkBox_22 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_22.setText(QtGui.QApplication.translate("affinityDialog", "CPU22", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout.addWidget(self.checkBox_22, 6, 2, 1, 1)
        self.checkBox_30 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_30.setText(QtGui.QApplication.translate("affinityDialog", "CPU30", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.gridLayout.addWidget(self.checkBox_30, 6, 3, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_7.setText(QtGui.QApplication.translate("affinityDialog", "CPU7", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 7, 0, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_15.setText(QtGui.QApplication.translate("affinityDialog", "CPU15", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridLayout.addWidget(self.checkBox_15, 7, 1, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_23.setText(QtGui.QApplication.translate("affinityDialog", "CPU23", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout.addWidget(self.checkBox_23, 7, 2, 1, 1)
        self.checkBox_31 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_31.setText(QtGui.QApplication.translate("affinityDialog", "CPU31", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.gridLayout.addWidget(self.checkBox_31, 7, 3, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(affinityDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(affinityDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), affinityDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), affinityDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(affinityDialog)

    def retranslateUi(self, affinityDialog):
        pass

