# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networkinformation.ui'
#
# Created: Fri May 14 15:27:00 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_35 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxNetworkCard_00 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_00.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_00.setObjectName("groupBoxNetworkCard_00")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxNetworkCard_00)
        self.verticalLayout.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.qwtPlotNetworkCardHistory_00 = Qwt5.QwtPlot(self.groupBoxNetworkCard_00)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_00.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_00.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_00.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_00.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_00.setObjectName("qwtPlotNetworkCardHistory_00")
        self.verticalLayout.addWidget(self.qwtPlotNetworkCardHistory_00)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_00, 0, 0, 1, 1)
        self.groupBoxNetworkCard_01 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_01.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_01.setObjectName("groupBoxNetworkCard_01")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_01)
        self.verticalLayout_2.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qwtPlotNetworkCardHistory_01 = Qwt5.QwtPlot(self.groupBoxNetworkCard_01)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_01.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_01.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_01.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_01.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_01.setObjectName("qwtPlotNetworkCardHistory_01")
        self.verticalLayout_2.addWidget(self.qwtPlotNetworkCardHistory_01)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_01, 0, 1, 1, 1)
        self.groupBoxNetworkCard_02 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_02.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_02.setObjectName("groupBoxNetworkCard_02")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_02)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.qwtPlotNetworkCardHistory_02 = Qwt5.QwtPlot(self.groupBoxNetworkCard_02)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_02.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_02.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_02.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_02.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_02.setObjectName("qwtPlotNetworkCardHistory_02")
        self.verticalLayout_3.addWidget(self.qwtPlotNetworkCardHistory_02)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_02, 0, 2, 1, 1)
        self.groupBoxNetworkCard_03 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_03.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_03.setObjectName("groupBoxNetworkCard_03")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_03)
        self.verticalLayout_4.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.qwtPlotNetworkCardHistory_03 = Qwt5.QwtPlot(self.groupBoxNetworkCard_03)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_03.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_03.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_03.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_03.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_03.setObjectName("qwtPlotNetworkCardHistory_03")
        self.verticalLayout_4.addWidget(self.qwtPlotNetworkCardHistory_03)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_03, 0, 3, 1, 1)
        self.groupBoxNetworkCard_04 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_04.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_04.setObjectName("groupBoxNetworkCard_04")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_04)
        self.verticalLayout_5.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.qwtPlotNetworkCardHistory_04 = Qwt5.QwtPlot(self.groupBoxNetworkCard_04)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_04.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_04.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_04.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_04.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_04.setObjectName("qwtPlotNetworkCardHistory_04")
        self.verticalLayout_5.addWidget(self.qwtPlotNetworkCardHistory_04)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_04, 0, 4, 1, 1)
        self.groupBoxNetworkCard_05 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_05.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_05.setObjectName("groupBoxNetworkCard_05")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_05)
        self.verticalLayout_6.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.qwtPlotNetworkCardHistory_05 = Qwt5.QwtPlot(self.groupBoxNetworkCard_05)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_05.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_05.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_05.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_05.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_05.setObjectName("qwtPlotNetworkCardHistory_05")
        self.verticalLayout_6.addWidget(self.qwtPlotNetworkCardHistory_05)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_05, 0, 5, 1, 1)
        self.groupBoxNetworkCard_06 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_06.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_06.setObjectName("groupBoxNetworkCard_06")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_06)
        self.verticalLayout_8.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.qwtPlotNetworkCardHistory_06 = Qwt5.QwtPlot(self.groupBoxNetworkCard_06)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_06.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_06.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_06.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_06.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_06.setObjectName("qwtPlotNetworkCardHistory_06")
        self.verticalLayout_8.addWidget(self.qwtPlotNetworkCardHistory_06)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_06, 0, 6, 1, 1)
        self.groupBoxNetworkCard_07 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_07.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_07.setObjectName("groupBoxNetworkCard_07")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_07)
        self.verticalLayout_7.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.qwtPlotNetworkCardHistory_07 = Qwt5.QwtPlot(self.groupBoxNetworkCard_07)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_07.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_07.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_07.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_07.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_07.setObjectName("qwtPlotNetworkCardHistory_07")
        self.verticalLayout_7.addWidget(self.qwtPlotNetworkCardHistory_07)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_07, 0, 7, 1, 1)
        self.groupBoxNetworkCard_08 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_08.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_08.setObjectName("groupBoxNetworkCard_08")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_08)
        self.verticalLayout_11.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.qwtPlotNetworkCardHistory_08 = Qwt5.QwtPlot(self.groupBoxNetworkCard_08)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_08.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_08.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_08.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_08.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_08.setObjectName("qwtPlotNetworkCardHistory_08")
        self.verticalLayout_11.addWidget(self.qwtPlotNetworkCardHistory_08)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_08, 1, 0, 1, 1)
        self.groupBoxNetworkCard_09 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_09.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_09.setObjectName("groupBoxNetworkCard_09")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_09)
        self.verticalLayout_13.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.qwtPlotNetworkCardHistory_09 = Qwt5.QwtPlot(self.groupBoxNetworkCard_09)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_09.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_09.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_09.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_09.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_09.setObjectName("qwtPlotNetworkCardHistory_09")
        self.verticalLayout_13.addWidget(self.qwtPlotNetworkCardHistory_09)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_09, 1, 1, 1, 1)
        self.groupBoxNetworkCard_10 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_10.setObjectName("groupBoxNetworkCard_10")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_10)
        self.verticalLayout_18.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.qwtPlotNetworkCardHistory_10 = Qwt5.QwtPlot(self.groupBoxNetworkCard_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_10.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_10.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_10.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_10.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_10.setObjectName("qwtPlotNetworkCardHistory_10")
        self.verticalLayout_18.addWidget(self.qwtPlotNetworkCardHistory_10)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_10, 1, 2, 1, 1)
        self.groupBoxNetworkCard_11 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_11.setObjectName("groupBoxNetworkCard_11")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_11)
        self.verticalLayout_19.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.qwtPlotNetworkCardHistory_11 = Qwt5.QwtPlot(self.groupBoxNetworkCard_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_11.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_11.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_11.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_11.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_11.setObjectName("qwtPlotNetworkCardHistory_11")
        self.verticalLayout_19.addWidget(self.qwtPlotNetworkCardHistory_11)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_11, 1, 3, 1, 1)
        self.groupBoxNetworkCard_12 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_12.setObjectName("groupBoxNetworkCard_12")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_12)
        self.verticalLayout_20.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.qwtPlotNetworkCardHistory_12 = Qwt5.QwtPlot(self.groupBoxNetworkCard_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_12.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_12.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_12.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_12.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_12.setObjectName("qwtPlotNetworkCardHistory_12")
        self.verticalLayout_20.addWidget(self.qwtPlotNetworkCardHistory_12)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_12, 1, 4, 1, 1)
        self.groupBoxNetworkCard_13 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_13.setObjectName("groupBoxNetworkCard_13")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_13)
        self.verticalLayout_21.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.qwtPlotNetworkCardHistory_13 = Qwt5.QwtPlot(self.groupBoxNetworkCard_13)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_13.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_13.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_13.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_13.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_13.setObjectName("qwtPlotNetworkCardHistory_13")
        self.verticalLayout_21.addWidget(self.qwtPlotNetworkCardHistory_13)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_13, 1, 5, 1, 1)
        self.groupBoxNetworkCard_14 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_14.setObjectName("groupBoxNetworkCard_14")
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_14)
        self.verticalLayout_22.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.qwtPlotNetworkCardHistory_14 = Qwt5.QwtPlot(self.groupBoxNetworkCard_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_14.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_14.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_14.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_14.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_14.setObjectName("qwtPlotNetworkCardHistory_14")
        self.verticalLayout_22.addWidget(self.qwtPlotNetworkCardHistory_14)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_14, 1, 6, 1, 1)
        self.groupBoxNetworkCard_15 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_15.setObjectName("groupBoxNetworkCard_15")
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_15)
        self.verticalLayout_23.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.qwtPlotNetworkCardHistory_15 = Qwt5.QwtPlot(self.groupBoxNetworkCard_15)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_15.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_15.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_15.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_15.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_15.setObjectName("qwtPlotNetworkCardHistory_15")
        self.verticalLayout_23.addWidget(self.qwtPlotNetworkCardHistory_15)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_15, 1, 7, 1, 1)
        self.groupBoxNetworkCard_16 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_16.setObjectName("groupBoxNetworkCard_16")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_16)
        self.verticalLayout_24.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.qwtPlotNetworkCardHistory_16 = Qwt5.QwtPlot(self.groupBoxNetworkCard_16)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_16.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_16.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_16.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_16.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_16.setObjectName("qwtPlotNetworkCardHistory_16")
        self.verticalLayout_24.addWidget(self.qwtPlotNetworkCardHistory_16)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_16, 2, 0, 1, 1)
        self.groupBoxNetworkCard_17 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_17.setObjectName("groupBoxNetworkCard_17")
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_17)
        self.verticalLayout_25.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.qwtPlotNetworkCardHistory_17 = Qwt5.QwtPlot(self.groupBoxNetworkCard_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_17.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_17.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_17.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_17.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_17.setObjectName("qwtPlotNetworkCardHistory_17")
        self.verticalLayout_25.addWidget(self.qwtPlotNetworkCardHistory_17)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_17, 2, 1, 1, 1)
        self.groupBoxNetworkCard_18 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_18.setObjectName("groupBoxNetworkCard_18")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_18)
        self.verticalLayout_26.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.qwtPlotNetworkCardHistory_18 = Qwt5.QwtPlot(self.groupBoxNetworkCard_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_18.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_18.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_18.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_18.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_18.setObjectName("qwtPlotNetworkCardHistory_18")
        self.verticalLayout_26.addWidget(self.qwtPlotNetworkCardHistory_18)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_18, 2, 2, 1, 1)
        self.groupBoxNetworkCard_19 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_19.setObjectName("groupBoxNetworkCard_19")
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_19)
        self.verticalLayout_27.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.qwtPlotNetworkCardHistory_19 = Qwt5.QwtPlot(self.groupBoxNetworkCard_19)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_19.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_19.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_19.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_19.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_19.setObjectName("qwtPlotNetworkCardHistory_19")
        self.verticalLayout_27.addWidget(self.qwtPlotNetworkCardHistory_19)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_19, 2, 3, 1, 1)
        self.groupBoxNetworkCard_20 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_20.setObjectName("groupBoxNetworkCard_20")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_20)
        self.verticalLayout_28.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.qwtPlotNetworkCardHistory_20 = Qwt5.QwtPlot(self.groupBoxNetworkCard_20)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_20.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_20.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_20.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_20.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_20.setObjectName("qwtPlotNetworkCardHistory_20")
        self.verticalLayout_28.addWidget(self.qwtPlotNetworkCardHistory_20)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_20, 2, 4, 1, 1)
        self.groupBoxNetworkCard_21 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_21.setObjectName("groupBoxNetworkCard_21")
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_21)
        self.verticalLayout_29.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.qwtPlotNetworkCardHistory_21 = Qwt5.QwtPlot(self.groupBoxNetworkCard_21)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_21.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_21.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_21.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_21.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_21.setObjectName("qwtPlotNetworkCardHistory_21")
        self.verticalLayout_29.addWidget(self.qwtPlotNetworkCardHistory_21)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_21, 2, 5, 1, 1)
        self.groupBoxNetworkCard_22 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_22.setObjectName("groupBoxNetworkCard_22")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_22)
        self.verticalLayout_30.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.qwtPlotNetworkCardHistory_22 = Qwt5.QwtPlot(self.groupBoxNetworkCard_22)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_22.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_22.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_22.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_22.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_22.setObjectName("qwtPlotNetworkCardHistory_22")
        self.verticalLayout_30.addWidget(self.qwtPlotNetworkCardHistory_22)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_22, 2, 6, 1, 1)
        self.groupBoxNetworkCard_23 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_23.setObjectName("groupBoxNetworkCard_23")
        self.verticalLayout_31 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_23)
        self.verticalLayout_31.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.qwtPlotNetworkCardHistory_23 = Qwt5.QwtPlot(self.groupBoxNetworkCard_23)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_23.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_23.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_23.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_23.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_23.setObjectName("qwtPlotNetworkCardHistory_23")
        self.verticalLayout_31.addWidget(self.qwtPlotNetworkCardHistory_23)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_23, 2, 7, 1, 1)
        self.groupBoxNetworkCard_24 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_24.setObjectName("groupBoxNetworkCard_24")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_24)
        self.verticalLayout_32.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.qwtPlotNetworkCardHistory_24 = Qwt5.QwtPlot(self.groupBoxNetworkCard_24)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_24.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_24.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_24.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_24.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_24.setObjectName("qwtPlotNetworkCardHistory_24")
        self.verticalLayout_32.addWidget(self.qwtPlotNetworkCardHistory_24)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_24, 3, 0, 1, 1)
        self.groupBoxNetworkCard_25 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_25.setObjectName("groupBoxNetworkCard_25")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_25)
        self.verticalLayout_16.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.qwtPlotNetworkCardHistory_25 = Qwt5.QwtPlot(self.groupBoxNetworkCard_25)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_25.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_25.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_25.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_25.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_25.setObjectName("qwtPlotNetworkCardHistory_25")
        self.verticalLayout_16.addWidget(self.qwtPlotNetworkCardHistory_25)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_25, 3, 1, 1, 1)
        self.groupBoxNetworkCard_26 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_26.setObjectName("groupBoxNetworkCard_26")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_26)
        self.verticalLayout_14.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.qwtPlotNetworkCardHistory_26 = Qwt5.QwtPlot(self.groupBoxNetworkCard_26)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_26.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_26.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_26.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_26.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_26.setObjectName("qwtPlotNetworkCardHistory_26")
        self.verticalLayout_14.addWidget(self.qwtPlotNetworkCardHistory_26)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_26, 3, 2, 1, 1)
        self.groupBoxNetworkCard_27 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_27.setObjectName("groupBoxNetworkCard_27")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_27)
        self.verticalLayout_17.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.qwtPlotNetworkCardHistory_27 = Qwt5.QwtPlot(self.groupBoxNetworkCard_27)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_27.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_27.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_27.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_27.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_27.setObjectName("qwtPlotNetworkCardHistory_27")
        self.verticalLayout_17.addWidget(self.qwtPlotNetworkCardHistory_27)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_27, 3, 3, 1, 1)
        self.groupBoxNetworkCard_28 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_28.setObjectName("groupBoxNetworkCard_28")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_28)
        self.verticalLayout_12.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.qwtPlotNetworkCardHistory_28 = Qwt5.QwtPlot(self.groupBoxNetworkCard_28)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_28.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_28.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_28.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_28.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_28.setObjectName("qwtPlotNetworkCardHistory_28")
        self.verticalLayout_12.addWidget(self.qwtPlotNetworkCardHistory_28)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_28, 3, 4, 1, 1)
        self.groupBoxNetworkCard_29 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_29.setObjectName("groupBoxNetworkCard_29")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_29)
        self.verticalLayout_10.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.qwtPlotNetworkCardHistory_29 = Qwt5.QwtPlot(self.groupBoxNetworkCard_29)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_29.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_29.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_29.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_29.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_29.setObjectName("qwtPlotNetworkCardHistory_29")
        self.verticalLayout_10.addWidget(self.qwtPlotNetworkCardHistory_29)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_29, 3, 5, 1, 1)
        self.groupBoxNetworkCard_30 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_30.setObjectName("groupBoxNetworkCard_30")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_30)
        self.verticalLayout_9.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.qwtPlotNetworkCardHistory_30 = Qwt5.QwtPlot(self.groupBoxNetworkCard_30)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_30.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_30.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_30.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_30.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_30.setObjectName("qwtPlotNetworkCardHistory_30")
        self.verticalLayout_9.addWidget(self.qwtPlotNetworkCardHistory_30)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_30, 3, 6, 1, 1)
        self.groupBoxNetworkCard_31 = QtGui.QGroupBox(self.groupBox)
        self.groupBoxNetworkCard_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxNetworkCard_31.setObjectName("groupBoxNetworkCard_31")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBoxNetworkCard_31)
        self.verticalLayout_15.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.qwtPlotNetworkCardHistory_31 = Qwt5.QwtPlot(self.groupBoxNetworkCard_31)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotNetworkCardHistory_31.sizePolicy().hasHeightForWidth())
        self.qwtPlotNetworkCardHistory_31.setSizePolicy(sizePolicy)
        self.qwtPlotNetworkCardHistory_31.setMinimumSize(QtCore.QSize(25, 25))
        self.qwtPlotNetworkCardHistory_31.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotNetworkCardHistory_31.setObjectName("qwtPlotNetworkCardHistory_31")
        self.verticalLayout_15.addWidget(self.qwtPlotNetworkCardHistory_31)
        self.gridLayout.addWidget(self.groupBoxNetworkCard_31, 3, 7, 1, 1)
        self.verticalLayout_35.addWidget(self.groupBox)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 200))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tabWidget.setObjectName("tabWidget")
        self.tabOverview = QtGui.QWidget()
        self.tabOverview.setObjectName("tabOverview")
        self.label = QtGui.QLabel(self.tabOverview)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 18))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.tabOverview)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 60, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.tabOverview)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 60, 18))
        self.label_3.setObjectName("label_3")
        self.labelTotalError = QtGui.QLabel(self.tabOverview)
        self.labelTotalError.setGeometry(QtCore.QRect(90, 20, 60, 18))
        self.labelTotalError.setObjectName("labelTotalError")
        self.labelTotalDrops = QtGui.QLabel(self.tabOverview)
        self.labelTotalDrops.setGeometry(QtCore.QRect(90, 40, 60, 18))
        self.labelTotalDrops.setObjectName("labelTotalDrops")
        self.labelTotalCollisions = QtGui.QLabel(self.tabOverview)
        self.labelTotalCollisions.setGeometry(QtCore.QRect(90, 60, 60, 18))
        self.labelTotalCollisions.setObjectName("labelTotalCollisions")
        self.tabWidget.addTab(self.tabOverview, "")
        self.verticalLayout_33.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 25, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.buttonBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_33.addLayout(self.horizontalLayout_2)
        self.verticalLayout_35.addLayout(self.verticalLayout_33)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "System Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Network Usage History", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_00.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_01.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_02.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_03.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_04.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_05.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_06.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_07.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_08.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_09.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_10.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_11.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_12.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_13.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_14.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_15.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_16.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_17.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_18.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_19.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_20.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_21.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_22.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_23.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_24.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_25.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_26.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_27.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_28.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_29.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_30.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxNetworkCard_31.setTitle(QtGui.QApplication.translate("Dialog", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Errors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Collisions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Drops", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalError.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalDrops.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTotalCollisions.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverview), QtGui.QApplication.translate("Dialog", "Overview", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
