# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systeminformation.ui'
#
# Created: Sun Dec 15 11:46:40 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui



try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(614, 459)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.qwtPlotCpuHist_01 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_01.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_01.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_01.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_01.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_01.setObjectName(_fromUtf8("qwtPlotCpuHist_01"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_01, 0, 0, 1, 1)
        self.qwtPlotCpuHist_02 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_02.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_02.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_02.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_02.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_02.setObjectName(_fromUtf8("qwtPlotCpuHist_02"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_02, 0, 1, 1, 1)
        self.qwtPlotCpuHist_03 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_03.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_03.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_03.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_03.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_03.setObjectName(_fromUtf8("qwtPlotCpuHist_03"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_03, 0, 2, 1, 1)
        self.qwtPlotCpuHist_04 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_04.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_04.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_04.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_04.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_04.setObjectName(_fromUtf8("qwtPlotCpuHist_04"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_04, 0, 3, 1, 1)
        self.qwtPlotCpuHist_05 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_05.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_05.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_05.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_05.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_05.setObjectName(_fromUtf8("qwtPlotCpuHist_05"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_05, 0, 4, 1, 1)
        self.qwtPlotCpuHist_06 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_06.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_06.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_06.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_06.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_06.setObjectName(_fromUtf8("qwtPlotCpuHist_06"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_06, 0, 5, 1, 1)
        self.qwtPlotCpuHist_07 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_07.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_07.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_07.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_07.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_07.setObjectName(_fromUtf8("qwtPlotCpuHist_07"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_07, 0, 6, 1, 1)
        self.qwtPlotCpuHist_08 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_08.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_08.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_08.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_08.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_08.setObjectName(_fromUtf8("qwtPlotCpuHist_08"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_08, 0, 7, 1, 1)
        self.qwtPlotCpuHist_09 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_09.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_09.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_09.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_09.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_09.setObjectName(_fromUtf8("qwtPlotCpuHist_09"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_09, 1, 0, 1, 1)
        self.qwtPlotCpuHist_10 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_10.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_10.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_10.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_10.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_10.setObjectName(_fromUtf8("qwtPlotCpuHist_10"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_10, 1, 1, 1, 1)
        self.qwtPlotCpuHist_11 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_11.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_11.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_11.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_11.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_11.setObjectName(_fromUtf8("qwtPlotCpuHist_11"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_11, 1, 2, 1, 1)
        self.qwtPlotCpuHist_12 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_12.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_12.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_12.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_12.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_12.setObjectName(_fromUtf8("qwtPlotCpuHist_12"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_12, 1, 3, 1, 1)
        self.qwtPlotCpuHist_13 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_13.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_13.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_13.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_13.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_13.setObjectName(_fromUtf8("qwtPlotCpuHist_13"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_13, 1, 4, 1, 1)
        self.qwtPlotCpuHist_14 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_14.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_14.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_14.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_14.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_14.setObjectName(_fromUtf8("qwtPlotCpuHist_14"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_14, 1, 5, 1, 1)
        self.qwtPlotCpuHist_15 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_15.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_15.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_15.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_15.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_15.setObjectName(_fromUtf8("qwtPlotCpuHist_15"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_15, 1, 6, 1, 1)
        self.qwtPlotCpuHist_16 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_16.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_16.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_16.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_16.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_16.setObjectName(_fromUtf8("qwtPlotCpuHist_16"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_16, 1, 7, 1, 1)
        self.qwtPlotCpuHist_17 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_17.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_17.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_17.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_17.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_17.setObjectName(_fromUtf8("qwtPlotCpuHist_17"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_17, 2, 0, 1, 1)
        self.qwtPlotCpuHist_18 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_18.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_18.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_18.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_18.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_18.setObjectName(_fromUtf8("qwtPlotCpuHist_18"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_18, 2, 1, 1, 1)
        self.qwtPlotCpuHist_19 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_19.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_19.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_19.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_19.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_19.setObjectName(_fromUtf8("qwtPlotCpuHist_19"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_19, 2, 2, 1, 1)
        self.qwtPlotCpuHist_20 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_20.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_20.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_20.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_20.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_20.setObjectName(_fromUtf8("qwtPlotCpuHist_20"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_20, 2, 3, 1, 1)
        self.qwtPlotCpuHist_21 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_21.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_21.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_21.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_21.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_21.setObjectName(_fromUtf8("qwtPlotCpuHist_21"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_21, 2, 4, 1, 1)
        self.qwtPlotCpuHist_22 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_22.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_22.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_22.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_22.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_22.setObjectName(_fromUtf8("qwtPlotCpuHist_22"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_22, 2, 5, 1, 1)
        self.qwtPlotCpuHist_23 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_23.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_23.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_23.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_23.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_23.setObjectName(_fromUtf8("qwtPlotCpuHist_23"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_23, 2, 6, 1, 1)
        self.qwtPlotCpuHist_24 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_24.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_24.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_24.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_24.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_24.setObjectName(_fromUtf8("qwtPlotCpuHist_24"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_24, 2, 7, 1, 1)
        self.qwtPlotCpuHist_25 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_25.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_25.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_25.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_25.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_25.setObjectName(_fromUtf8("qwtPlotCpuHist_25"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_25, 3, 0, 1, 1)
        self.qwtPlotCpuHist_26 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_26.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_26.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_26.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_26.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_26.setObjectName(_fromUtf8("qwtPlotCpuHist_26"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_26, 3, 1, 1, 1)
        self.qwtPlotCpuHist_27 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_27.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_27.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_27.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_27.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_27.setObjectName(_fromUtf8("qwtPlotCpuHist_27"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_27, 3, 2, 1, 1)
        self.qwtPlotCpuHist_28 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_28.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_28.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_28.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_28.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_28.setObjectName(_fromUtf8("qwtPlotCpuHist_28"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_28, 3, 3, 1, 1)
        self.qwtPlotCpuHist_29 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_29.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_29.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_29.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_29.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_29.setObjectName(_fromUtf8("qwtPlotCpuHist_29"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_29, 3, 4, 1, 1)
        self.qwtPlotCpuHist_30 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_30.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_30.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_30.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_30.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_30.setObjectName(_fromUtf8("qwtPlotCpuHist_30"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_30, 3, 5, 1, 1)
        self.qwtPlotCpuHist_31 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_31.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_31.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_31.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_31.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_31.setObjectName(_fromUtf8("qwtPlotCpuHist_31"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_31, 3, 6, 1, 1)
        self.qwtPlotCpuHist_32 = Qwt5.QwtPlot(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_32.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_32.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_32.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_32.setSizeIncrement(QtCore.QSize(2, 2))
        self.qwtPlotCpuHist_32.setObjectName(_fromUtf8("qwtPlotCpuHist_32"))
        self.gridLayout.addWidget(self.qwtPlotCpuHist_32, 3, 7, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.qwtPlotMemoryHist = Qwt5.QwtPlot(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotMemoryHist.sizePolicy().hasHeightForWidth())
        self.qwtPlotMemoryHist.setSizePolicy(sizePolicy)
        self.qwtPlotMemoryHist.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotMemoryHist.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotMemoryHist.setObjectName(_fromUtf8("qwtPlotMemoryHist"))
        self.gridLayout_3.addWidget(self.qwtPlotMemoryHist, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.memTotal = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.memTotal.sizePolicy().hasHeightForWidth())
        self.memTotal.setSizePolicy(sizePolicy)
        self.memTotal.setMinimumSize(QtCore.QSize(40, 10))
        self.memTotal.setBaseSize(QtCore.QSize(60, 0))
        self.memTotal.setObjectName(_fromUtf8("memTotal"))
        self.gridLayout_2.addWidget(self.memTotal, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(40, 10))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setMinimumSize(QtCore.QSize(40, 10))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.memUsed = QtGui.QLabel(self.groupBox_3)
        self.memUsed.setMinimumSize(QtCore.QSize(40, 10))
        self.memUsed.setObjectName(_fromUtf8("memUsed"))
        self.gridLayout_2.addWidget(self.memUsed, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(40, 10))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.memAvailable = QtGui.QLabel(self.groupBox_3)
        self.memAvailable.setMinimumSize(QtCore.QSize(40, 10))
        self.memAvailable.setObjectName(_fromUtf8("memAvailable"))
        self.gridLayout_2.addWidget(self.memAvailable, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(40, 10))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.memBuffers = QtGui.QLabel(self.groupBox_3)
        self.memBuffers.setMinimumSize(QtCore.QSize(40, 10))
        self.memBuffers.setObjectName(_fromUtf8("memBuffers"))
        self.gridLayout_2.addWidget(self.memBuffers, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(40, 10))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.memCached = QtGui.QLabel(self.groupBox_3)
        self.memCached.setMinimumSize(QtCore.QSize(40, 10))
        self.memCached.setObjectName(_fromUtf8("memCached"))
        self.gridLayout_2.addWidget(self.memCached, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setMinimumSize(QtCore.QSize(40, 10))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.swapUsed = QtGui.QLabel(self.groupBox_3)
        self.swapUsed.setObjectName(_fromUtf8("swapUsed"))
        self.gridLayout_2.addWidget(self.swapUsed, 5, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setMinimumSize(QtCore.QSize(40, 10))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.last1minUtil = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last1minUtil.sizePolicy().hasHeightForWidth())
        self.last1minUtil.setSizePolicy(sizePolicy)
        self.last1minUtil.setMinimumSize(QtCore.QSize(40, 10))
        self.last1minUtil.setBaseSize(QtCore.QSize(60, 0))
        self.last1minUtil.setObjectName(_fromUtf8("last1minUtil"))
        self.gridLayout_4.addWidget(self.last1minUtil, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setMinimumSize(QtCore.QSize(40, 10))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.last5minUtil = QtGui.QLabel(self.groupBox_4)
        self.last5minUtil.setMinimumSize(QtCore.QSize(40, 10))
        self.last5minUtil.setObjectName(_fromUtf8("last5minUtil"))
        self.gridLayout_4.addWidget(self.last5minUtil, 1, 1, 1, 1)
        self.ddddd = QtGui.QLabel(self.groupBox_4)
        self.ddddd.setMinimumSize(QtCore.QSize(40, 10))
        self.ddddd.setObjectName(_fromUtf8("ddddd"))
        self.gridLayout_4.addWidget(self.ddddd, 2, 0, 1, 1)
        self.last10minUtil = QtGui.QLabel(self.groupBox_4)
        self.last10minUtil.setMinimumSize(QtCore.QSize(40, 10))
        self.last10minUtil.setObjectName(_fromUtf8("last10minUtil"))
        self.gridLayout_4.addWidget(self.last10minUtil, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setMinimumSize(QtCore.QSize(40, 10))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.procs = QtGui.QLabel(self.groupBox_4)
        self.procs.setMinimumSize(QtCore.QSize(40, 10))
        self.procs.setObjectName(_fromUtf8("procs"))
        self.gridLayout_4.addWidget(self.procs, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setMinimumSize(QtCore.QSize(40, 10))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.lastpid = QtGui.QLabel(self.groupBox_4)
        self.lastpid.setMinimumSize(QtCore.QSize(40, 10))
        self.lastpid.setObjectName(_fromUtf8("lastpid"))
        self.gridLayout_4.addWidget(self.lastpid, 4, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(318, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "System Information", None))
        self.groupBox.setTitle(_translate("Dialog", "CPU Usage History", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Physical Memory History", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Physical Memory (K)", None))
        self.memTotal.setText(_translate("Dialog", "0", None))
        self.label.setText(_translate("Dialog", "Total", None))
        self.label_3.setText(_translate("Dialog", "Used", None))
        self.memUsed.setText(_translate("Dialog", "0", None))
        self.label_2.setText(_translate("Dialog", "Available", None))
        self.memAvailable.setText(_translate("Dialog", "0", None))
        self.label_4.setText(_translate("Dialog", "Buffers", None))
        self.memBuffers.setText(_translate("Dialog", "0", None))
        self.label_5.setText(_translate("Dialog", "Cached", None))
        self.memCached.setText(_translate("Dialog", "0", None))
        self.label_8.setText(_translate("Dialog", "Swap used", None))
        self.swapUsed.setText(_translate("Dialog", "0", None))
        self.groupBox_4.setTitle(_translate("Dialog", "System Usage (averages)", None))
        self.label_6.setText(_translate("Dialog", "last 1 minute utilisation (CPU/IO)", None))
        self.last1minUtil.setText(_translate("Dialog", "0", None))
        self.label_7.setText(_translate("Dialog", "Last 5 minutes utilisation (CPU/IO)", None))
        self.last5minUtil.setText(_translate("Dialog", "0", None))
        self.ddddd.setText(_translate("Dialog", "Last 10 minutes utilisation (CPU/IO)", None))
        self.last10minUtil.setText(_translate("Dialog", "0", None))
        self.label_9.setText(_translate("Dialog", "Running / total number of processes", None))
        self.procs.setText(_translate("Dialog", "0", None))
        self.label_10.setText(_translate("Dialog", "Last used PID", None))
        self.lastpid.setText(_translate("Dialog", "0", None))


from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

